name: Release

on:
  push:
    # https://github.com/dani-garcia/vaultwarden/blob/main/.github/workflows/release.yml
    tags:
      - '[1-2].[0-9]+.[0-9]+'

jobs:
  get-artifacts-list:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_workflows
        with:
          route: GET /repos/{owner}/{repo}/actions/workflows
          owner: dani-garcia
          repo: vaultwarden
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: cloudposse/github-action-jq@0.4.0
        id: match_workflow_id
        raw-output: '${{ steps.get_workflows.outputs.workflows }}'
        script: |-
          .[] | select(.name=="Release") | .id

      - run: "echo latest release: '${{ steps.match_workflow_id.outputs }}'"
