name: Log latest release
on:
  push:
    branches:
      - master

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_workflows
        with:
          route: GET /repos/{owner}/{repo}/actions/workflows
          owner: dani-garcia
          repo: vaultwarden
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo ${{ fromJSON(steps.get_workflows.outputs.data.workflows) }}"
