name: Release

on:
  push:
    branches:
      - master

    # https://github.com/dani-garcia/vaultwarden/blob/main/.github/workflows/release.yml
    tags:
      - '[1-2].[0-9]+.[0-9]+'

jobs:
  get-artifacts-list:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_workflows
        with:
          route: GET /repos/dani-garcia/vaultwarden/actions/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: cloudposse/github-action-jq@0.4.0
        id: match_workflow_id
        with:
          input: '${{ steps.get_workflows.outputs.workflows }}'
          script: |-
            .[] | select(.name=="Release") | .id

      - run: "echo workflow_id: '${{ steps.match_workflow_id.outputs }}'"
